### ISSUE TITLE
--help should exit

### ISSUE THREAD

**Issue by erikcorry** [toitlang/pkg-cli#11]
If the user invokes the command with --help, and hits the autogenerated --help support then the program should exit with code zero and not return from Command.run.  This way the programmer does not have to do anything special to get automatic --help support.

**Comment by floitsch** [comment]
I'm not sure about that.
I generally avoid 'exit' calls as much as possible. They make testing harder, and get in the way when something is used in a library.

The pattern for the cli library is generally to have `run` as the last line of the main program, and let the cmd do all the work. As such this scenario feels pretty unlikely.
